objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <defaultValue>&apos;Agriculture&apos;</defaultValue>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Industry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Code__c</fullName>
        <label>Project Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Apparel</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Biotechnology</fullName>
    </customValue>
    <customValue>
        <fullName>Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Education</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Energy</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Environmental</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Food &amp; Beverage</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Not For Profit</fullName>
    </customValue>
    <customValue>
        <fullName>Recreation</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Shipping</fullName>
    </customValue>
    <customValue>
        <fullName>Technology</fullName>
    </customValue>
    <customValue>
        <fullName>Telecommunications</fullName>
    </customValue>
    <customValue>
        <fullName>Transportation</fullName>
    </customValue>
    <masterLabel>Industry</masterLabel>
</GlobalValueSet>

classes/NewProjectCtrl.cls
public class NewProjectCtrl {
 @AuraEnabled
    public static String createOpp(Opportunity newRec) {
        try{
            insert newRec;
            return newRec.Id;
        }catch(Exception ex){
            return 'Error'+ex.getMessage();
        }
    }
    @AuraEnabled
    public static Integer generateChangeRequestCode(String accId,String projCode) {
        //List<Opportunity> lstOpp ;
        List<Integer> lstChangeNumber = new List<Integer>();
        for(Opportunity opp: [SELECT Id,AccountId, Project_Code__c FROM Opportunity WHERE AccountId = :accId]){
            if(String.isNotBlank(opp.Project_Code__c)){
				//String industryType = lstOldProjCode.get(1);
                if(opp.Project_Code__c.contains(projCode)){
                    String changeCode =(opp.Project_Code__c).right(3);
                    Integer changeCodeNum  = Integer.valueOf(changeCode);
                    lstChangeNumber.add(changeCodeNum); 
               }
            }
        }
        lstChangeNumber.sort();
        system.debug('lstChangeNumber****'+lstChangeNumber);
        system.debug('Hieghest lstChangeNumber ****'+lstChangeNumber.get(lstChangeNumber.size()-1));
        Integer changeRequestNum = (lstChangeNumber.get(lstChangeNumber.size()-1))+1;
        return changeRequestNum;
    }
    @AuraEnabled
    public static Integer generateProjectCode(String accId, String accIndustry) {
        //List<Opportunity> lstOpp ;
        Integer newProjectCode = 0000;
        List<Integer> lstProjNumber = new List<Integer>();
        for(Opportunity opp : [SELECT Id,AccountId, Project_Code__c FROM Opportunity WHERE AccountId = :accId AND Industry__c =:accIndustry]){
            if(String.isNotBlank(opp.Project_Code__c)){
                List<String> lstOldProjCode = (opp.Project_Code__c).split('-');
                Integer oldProjCode  = Integer.valueOf(lstOldProjCode.get(lstOldProjCode.size()-2));
                system.debug('oldProjCode'+oldProjCode);
                lstProjNumber.add(oldProjCode);
            }
            //Integer changeCode = Integer.parseInt((opp.Project_Code__c).right(3));
        }
        if(!lstProjNumber.isEmpty()){
            lstProjNumber.sort();
            newProjectCode = lstProjNumber.get(lstProjNumber.size()-1);
            system.debug('list sort num'+newProjectCode);
        }
        newProjectCode = newProjectCode + 1;
        system.debug('after adding one newProjectCode'+newProjectCode);
        return newProjectCode;
    }
    
  /*  @AuraEnabled
    public static map<String,List<String>> getFieldsSets(){
        System.debug('getFieldSets####>');
        Map<String, Schema.FieldSet> FsMap = Schema.SObjectType.Opportunity.fieldSets.getMap();
        List<Schema.FieldSet> lstField= new List<Schema.FieldSet>();
        Schema.SObjectType sObj = Schema.getGlobalDescribe().get('Opportunity');
        Map<String,List<String>> mapFieldSet = new Map<String,List<String>>();
         System.debug('FsMap.keyset()####>' + FsMap.keyset());
        for(String fieldSetName : FsMap.keyset()) {
            List<String> lstFieldApi =new List<String>();
            for(Schema.FieldSetMember fieldMember : sObj.getDescribe().fieldSets.getMap().get(fieldSetName).getFields()){
                lstFieldApi.add(fieldMember.getFieldPath());
            }
            mapFieldSet.put(fieldSetName, lstFieldApi);
        }
        return mapFieldSet;
    } */
}